# ----------------------------------------------------------------------- #
#
# 1. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d
#
# 2. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d --build
# 2 - Forces a rebuild of all container images
#
# ----------------------------------------------------------------------- #

version: '3.9'

services:

# Zookeeper service to co-ordinate and manage Kafka brokers (cluster)
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - spring

# Kafka Broker service for messaging and streaming data between our microservices
  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.5.0
    ports:
      # External connections (outside the Docker)
      - "9092:9092"
      # Internal connections (inside the Docker)
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - spring

# Kafka UI -service for monitoring kafka topics
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - broker
    networks:
      - spring


networks:
  spring:
    driver: bridge


